### ISSUE TITLE
Problem with format of script

### ISSUE THREAD

**Issue by AliM1988** [pharmarat/Ubuntu-Desktop-Installation-Script#1]
When I run ./install.sh , I get this error:
`-bash: ./install.sh: /bin/bash^M: bad interpreter: No such file or directory`

The error you're encountering (/bin/bash^M: bad interpreter: No such file or directory) indicates an issue with the line endings in your shell script. The ^M character is a carriage return (CR) character, which is part of Windows line endings.

I can fix this issue by converting the line endings to Unix format using dos2unix .
dos2unix install.sh

Please upload correct version of install.sh

**Comment by pharmarat** [comment]
Thanks for reminding me to fix this! Should be okay now
